### ISSUE TITLE
Convert XMLRPC response to UTF-8

### ISSUE THREAD

**Issue by kalatabe** [DarkaOnLine/Ripcord#2]
The `xmlrpc_decode` function in Client.php's `__call()` magic method does not specify an encoding as second parameter and the default is "iso-8859-1", so any UTF symbols such as accented characters and German Umlauts end up garbled. 

For example, if the function call on line 187 is refactored to this:

 `xmlrpc_decode(xmlrpc_decode($response, 'utf-8');`

then the following response array contains the proper symbols:

```
array(6) [
  "name": "Julian Brandenburg",
  "address": "Brüsseler Str. 999999, 51149 Köln",
  "building": "16",
  "active": true,
  "owner": "My Company GmbH",
  "create_date": "01.08.2016",
]
```

However, omitting the second parameter (as it is now) results in this:

```
  "name": "Julian Brandenburg",
  "address": "Br�sseler Str. 999999, 51149 K�ln",
  "building": "16",
  "active": true,
  "owner": "My Company GmbH",
  "create_date": "01.08.2016"
```

Would you consider accepting a pull request for this? After all, despite PHP's tragic history of (not) supporting UTF and Unicode, it's 2016 already and we need to be prepared for things like that :)

**Comment by DarkaOnLine** [comment]
It is not enough to call just `xmlrpc_decode($response, 'utf-8')` once? 

Either way the pull request is always welcome!

**Comment by kalatabe** [comment]
Yes, that's exactly what I meant, sorry if my original message was unclear. I'll try to work something out in the next few days
